"""Update tables, delete fields

Revision ID: 9b3559dff4dc
Revises: 9fd6542a0d1a
Create Date: 2024-11-06 16:09:17.597216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9b3559dff4dc"
down_revision: Union[str, None] = "9fd6542a0d1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tables", "guests_def")
    op.drop_column("tables", "guests_now")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tables",
        sa.Column(
            "guests_now",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tables",
        sa.Column(
            "guests_def",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
